// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB36Qjht3tGe7I249mNRdDyahuDWy7sNiI',
    appId: '1:843469736202:web:deba881a0991055c2812f3',
    messagingSenderId: '843469736202',
    projectId: 'alu-connect-f510a',
    authDomain: 'alu-connect-f510a.firebaseapp.com',
    storageBucket: 'alu-connect-f510a.firebasestorage.app',
    measurementId: 'G-FFGQYQJ7XS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB83WkJyvznR6EIAnFOCrUIgm0gLk75RjM',
    appId: '1:843469736202:android:ca5d2b3a32da04ec2812f3',
    messagingSenderId: '843469736202',
    projectId: 'alu-connect-f510a',
    storageBucket: 'alu-connect-f510a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbgf0hD7Tb_d0EuySSH6W4rRd1Aku0yYU',
    appId: '1:843469736202:ios:fe578798f02cd29b2812f3',
    messagingSenderId: '843469736202',
    projectId: 'alu-connect-f510a',
    storageBucket: 'alu-connect-f510a.firebasestorage.app',
    iosBundleId: 'com.example.aluConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbgf0hD7Tb_d0EuySSH6W4rRd1Aku0yYU',
    appId: '1:843469736202:ios:fe578798f02cd29b2812f3',
    messagingSenderId: '843469736202',
    projectId: 'alu-connect-f510a',
    storageBucket: 'alu-connect-f510a.firebasestorage.app',
    iosBundleId: 'com.example.aluConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB36Qjht3tGe7I249mNRdDyahuDWy7sNiI',
    appId: '1:843469736202:web:e0e3e5ba13d8f3632812f3',
    messagingSenderId: '843469736202',
    projectId: 'alu-connect-f510a',
    authDomain: 'alu-connect-f510a.firebaseapp.com',
    storageBucket: 'alu-connect-f510a.firebasestorage.app',
    measurementId: 'G-K7HXX5P0R6',
  );
}
